<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/24
 * Time: 16:58
 */

namespace app\api\service;

use libs\Pagination;

class AdminPagination extends Pagination
{
    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }
}